version: '3'
services:
  php82:
    build: ./docker/php82
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - '9000:9000'
    depends_on:
      - nginx
    networks:
      - adpega_network
  nginx:
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - adpega_network

networks:
  adpega_network: