version: '3'
services:
  php82:
    build: ./docker/php82
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - '9000:9000'
    depends_on:
      - nginx
    networks:
      - adpega_network
  nginx:
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - adpega_network
  mysql81:
    image: mysql:8.1
    container_name: mysql
    ports:
      - "3306:3307"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: adpega_example
      MYSQL_USER: adpega
      MYSQL_PASSWORD: adpega
      TZ: Asia/Tokyo
    volumes:
      - ./docker/mysql81/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql81/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql81/data:/var/lib/mysql
    restart: always
    networks:
      - adpega_network
  redis70:
    image: redis:7.0-alpine
    container_name: redis
    volumes:
      - ./docker/redis70/data:/data
    ports:
      - "26379:6379"
      - "6379:6379"
    restart: always
    networks:
      - adpega_network

networks:
  adpega_network: