Feature: example
  In order to ...
  As a ...
  I need to ...

  Scenario: example
    When I access the root URL with the query string { user="Adpega" }
    Then the response body is "Hello World, Adpega!"
